{
  "hash": "e156a5ebb5cd239d8f087288166517fd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Rice GWAS\"\nsubtitle: \"$p \\\\approx 158{,}000$ SNPs, $n = 1{,}155$ rice accessions, a known grain-length locus\"\n---\n\n::: {.callout-note appearance=\"minimal\"}\nThis demo uses pre-computed results — the raw genotype data is too large to ship with this site. The code shows what `combss` was called with; the figures below were produced by that call.\n:::\n\n## The biology\n\nGrain length is one of the most economically important traits in rice breeding. The major effect locus has been mapped to the **GS3 gene on chromosome 3**, identified independently by multiple GWAS groups using thousands of accessions.\n\nCan COMBSS recover this locus *de novo* from raw SNP data, working at the scale of a real GWAS?\n\n## The data\n\n- $n = 1{,}155$ rice accessions (3K Rice Genomes Project subset)\n- $p = 158{,}210$ SNPs after QC (MAF filter, call-rate filter)\n- Binary response: long-grain vs short-grain (threshold at 6 mm)\n- Population stratification corrected via the top principal components of the kinship matrix\n\nSource: McCouch et al. (2016), *3,000 rice genomes project*. Data preparation and QC are described in Mathur, Liquet, Muller, Moka (2026).\n\n## Running COMBSS (sketch)\n\nOnce `dataYX` has columns `[y, PCs..., SNP1, SNP2, ..., SNP_p]`:\n\n::: {.panel-tabset group=\"lang\"}\n\n## R\n\n```r\nlibrary(combss)\n\ny       <- dataYX$y\nx_snps  <- as.matrix(dataYX[, -c(1, 2)])   # drop y and intercept-like column\n\nfit_rice <- combss(x_snps, y,\n                   family = \"binomial\",\n                   q = 10)\nfit_rice$subset_list\n```\n\n## Python\n\n```python\nfrom combss import logistic\n\ny_rice = dataYX[\"y\"].to_numpy()\nX_snps = dataYX.drop(columns=[\"y\", \"intercept\"]).to_numpy()\n\nfit_rice = logistic.model()\nfit_rice.fit(X_snps, y_rice, q=10, verbose=False)\nprint(fit_rice.subset_list)\n```\n\n:::\n\nThe call returns a nested-looking subset path for $k = 1, \\ldots, 10$. We tabulate the selected SNP indices below.\n\n## The selected SNPs\n\nThe model at each size $k$:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|    |k  |Selected                                                               |\n|:---|:--|:----------------------------------------------------------------------|\n|k1  |1  |43318                                                                  |\n|k2  |2  |43307, 43318                                                           |\n|k3  |3  |43307, 43313, 43318                                                    |\n|k4  |4  |43307, 43313, 43318, 66479                                             |\n|k5  |5  |43307, 43309, 43313, 43318, 66479                                      |\n|k6  |6  |43307, 43309, 43313, 43318, 66479, 66480                               |\n|k7  |7  |43304, 43307, 43313, 43318, 43359, 66479, 66480                        |\n|k8  |8  |43307, 43309, 43313, 43318, 43335, 66479, 66480, 157373                |\n|k9  |9  |43307, 43313, 43318, 43335, 43336, 66479, 66480, 157368, 157373        |\n|k10 |10 |43288, 43307, 43313, 43318, 43335, 43336, 66479, 66480, 157368, 157373 |\n\n\n:::\n:::\n\n\nThe single best SNP at $k = 1$ — index **43318** — falls inside the **GS3 gene region on chromosome 3**, the well-known grain-length locus. SNPs **43307, 43313** (chromosome 3 neighbours of GS3) enter at $k = 2, 3$. The cluster around **66479, 66480** (chromosome 5) and **157368, 157373** (chromosome 12) join the model as $k$ grows, picking up secondary loci known from independent GWAS.\n\n## Best-subset inclusion path\n\nThe full inclusion-path figure (Figure 4a in the paper):\n\n![Best-subset inclusion path for the rice GWAS. Each column is one selected SNP; each row a model size $k$. A blue tile means the SNP is selected at that $k$. SNPs are ordered by first-inclusion.](../figures/rice/snp_inclusion_path.png){fig-align=\"center\" width=\"90%\"}\n\nThe earliest-included SNPs are tightly clustered on chromosome 3 — the GS3 locus. Additional chromosomes contribute as $k$ grows.\n\n## Correlation among selected SNPs\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Correlation matrix of the SNPs selected across all model sizes. Strong off-diagonal blocks reveal linkage disequilibrium within each chromosomal cluster.](../figures/rice/snp_correlation_matrix.png)\n:::\n:::\n\n\nThe block-diagonal structure tells the right biological story: SNPs from the same chromosomal region are in strong linkage disequilibrium, while across chromosomes they are nearly uncorrelated.\n\n## Why this matters\n\n- COMBSS scans 158{,}210 SNPs in a few minutes on a laptop — the regime where exact best-subset is hopeless and lasso typically returns hundreds of correlated SNPs.\n- The single best SNP it returns lands on the **known** functional locus, with no prior biological input.\n- For a breeder, *ten SNPs* is a tractable downstream panel; *several hundred* is not.\n\n## Reference\n\nMcCouch, S. R. et al. (2016). *Open access resources for genome-wide association mapping in rice*. **Nature Communications** 7, 10532.\n\n::: {.page-nav}\n[← Previous: Khan SRBCT](03-khan.qmd)\n\n[Next: Comparisons →](05-comparisons.qmd)\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}